#!/bin/bash

# global variables not configurable in .conf file
programename="lamp"
parameter1=$1
parameter2=$2
configpath="./$programename.conf"
required_config_variables=("vm_domain" "vm_user" "vm_ip" "site" "terminal" "browser" "inputCssNames" "outputCssNames")

# special codes for text
text_white="\e[0m"
text_red="\e[31m"
text_blue="\e[34m"
text_yellow="\e[33m"
text_green="\e[32m"
line_clear="\033[0K\r"


# outline:
#   input commands:
#       lamp start: starts vm and all necessary services, then open appropriet editors, logs and sites 
#       lamp continue: open editors and logs from current terminal
#       lamp reload: reloads apache2 on vm
#       lamp restart: reboots vm then start all necessary services
#       lamp restart web: restart apache2 on vm
#       lamp stop: shutdown vm and libvirtd, then close appropriet editors, logs and sites
#       lamp stop vm: shutdown vm host only
#       lamp status: show status of vm, site, apache2, mysql...
#       lamp config: opens configuration file
#      
#       config required info: vm name, vm ip, to be enabled site name, web browser to use, terminal command
#       automatically aquire info: whether vm is running, whether required systemd services are running


# ==============================================================================================================================
# configuration retrieval
terminate_with_error () {
    echo -e "${text_red}Program terminating with final error: \n${1} ${text_white}"
    exit 1
}

retrieveConfig() {
    if [ -f $configpath ]; then
        source $configpath
        local missing
        missing=false
        for var in "${required_config_variables[@]}"; do
            if ! [[ -v $var ]]; then
                echo -e "${text_red}variable '$var' is missing${text_white}"
                local missing=true
            fi
        done

        if $missing; then
            terminate_with_error "Config file is missing variables \nCheck 'required_config_variables' at the start of this script for all variables needed"
        fi
    else
        terminate_with_error "${programename} cannot run without the config file \nMake sure an appropriate path is assigned to the varaible 'configpath' at the start of this script$"
    fi
}

retrieveConfig

# ==============================================================================================================================
# basic functions that don't rely on any other functions defined in the program

# "check_wait_repeate" is for checking a condition repeatedly at specified intervals, inorder to ensure a command has fully completed
# $1 is the condition function
# $2 is the timeout interval
# $3 is the number of timeouts
check_wait_repeate () {
    sleep "$2"
    local condition_value
    condition_value=$($1)
    if [ "$condition_value" = 1 ] ; then
        echo -e "${line_clear}${text_green}completed${text_white}                \n"
    elif [ "$condition_value" = 0 ] ; then
        if [ "$3" = 0 ] ; then
            echo -e "${line_clear}${text_red}timed out${text_white}               \n";
            terminate_with_error "condition not met"
        else
            local time_remaining
            time_remaining=$(python3 -c "print(round(${2} * ${3}, 1))")
            echo -en "${line_clear}${time_remaining} seconds until timeout"
            local remaining_intervals=$(( $3 - 1 ))
            check_wait_repeate "$1" "$2" "$remaining_intervals"
        fi
    fi
}

# gives integer values for state of the vm, where:
# value "1" means vm
check_vm_domain () {
    local state
    state=$(sudo virsh domstate "$vm_domain")
    case "${state}" in
        "running")
            echo 1
            ;;
        "paused")
            echo 2
            ;;
        "shut off")
            echo 0
            ;;
        *)
            terminate_with_error "unexpected vm state '$state', exiting"
            ;;
    esac
}

#pass the service name as the $1 (first) argument
check_systemd () {
    local state
    state=$(systemctl is-active "$1")
    if [ "$state" = "active" ]; then
        echo 1
    else 
        echo 0
    fi
}

# ==============================================================================================================================
# general functions

# "resume_vm" ensures vm is unsuspended
resume_vm () {
    sudo virsh resume "$vm_domain"
    condition_function () {
        local condition_vm_state
        condition_vm_state=$(check_vm_domain)
        if [ "$condition_vm_state" = 1 ]; then
            echo 1
        else
            echo 0
        fi
    }
    check_wait_repeate condition_function 0.2 3
}



# "start_vm" ensures vm is running
start_vm () {
    local vm_state
    vm_state=$(check_vm_domain)
    if [ "$vm_state" = 0 ] ; then
        sudo virsh start "$vm_domain"
        check_wait_repeate check_vm_domain 0.1 3
    else
        if [ "$vm_state" = 2 ] ; then
            echo -e "${text_yellow}vm was suspended, now resuming${text_white}"
            sudo virsh resume "$vm_domain"
        else
            echo -e "${text_yellow}$vm_domain already running${text_white}"
        fi
    fi
}

# "start_libirtd" ensures libvirtd is running
start_libvirtd () {
    local libvirtd_state
    libvirtd_state=$(check_systemd "libvirtd")
    if [ "$libvirtd_state" = 0 ] ; then
        echo starting libvirtd
        sudo systemctl start libvirtd
        condition_function () {
            check_systemd libvirtd
        }
        check_wait_repeate condition_function 0.2 3
    else
        echo -e "${text_yellow}libvirtd.service is already running${text_white}"
    fi
}


# "stop_vm" ensures vm is shut down gracefully
stop_vm () {
    local vm_state
    vm_state=$(check_vm_domain)
    if [ "$vm_state" = 0 ]; then
        echo -e "${text_yellow}$vm_domain not running${text_white}"
    else
        if [ "$vm_state" = 2 ]; then
            resume_vm
        fi
        sudo virsh shutdown "$vm_domain"
        condition_function () {
            local condition_vm_state
            condition_vm_state=$(check_vm_domain)
            if [ "$condition_vm_state" = 0 ]; then
                echo 1
            else
                echo 0
            fi
        }
        check_wait_repeate condition_function 0.4 5
    fi
}

# "stop_libvirtd" ensures vm_domain is shutoff before stopping libvirtd.socket and libvirtd
stop_libvirtd () {
    local service
    local service_state
    service="libvirtd"
    service_state=$(check_systemd $service)
    if [ "$service_state" = 1 ]; then
            stop_vm
            echo stopping libvirtd
            sudo systemctl stop libvirtd.socket
            sudo systemctl stop libvirtd
            condition_function() {
                local condition_service_state
                condition_service_state=$(check_systemd "$service")
                if [ "$condition_service_state" = 0 ]; then
                    echo 1
                else
                    echo 0
                fi
            }
            check_wait_repeate condition_function 0.1 3
    else
        echo -e "${text_yellow}libvirtd.service is not running${text_white}"
    fi
}





# ==============================================================================================================================
# parameter handlers


start_function () {
    echo 'lamp start: starts vm and all necessary services, then open appropriet editors, logs and sites'
    echo
    start_libvirtd
    start_vm
}

continue_function () {
    echo lamp continue: open editors and logs from current terminal
}

reload_function () {
    echo reloads apache2 on vm
}

restart_function () {
    if [ "$parameter2" = "web" ]; then
        echo restarts apache2 on vm
    else
        echo "reboots vm then start all necessary services"
    fi
}

stop_function () {
    if [ "$parameter2" = "vm" ]; then
            echo shutdown vm host only
    else
        echo "lamp stop: shutdown vm, then close appropriet editors, logs and sites"
        echo
        stop_libvirtd
    fi
}

status_function () {
    echo lamp status: show status of vm, site, apache2, mysql...
    echo
}

config_function () {
    echo lamp config: opens configuration file
}

test_function () {
    echo -e "${text_blue}doing test:${text_white}"
    condition_function(){
        echo 0
    }
    check_wait_repeate condition_function 0.5 5
}

# ==============================================================================================================================
# checking for paramenters

case "${parameter1}" in
    "start")
        start_function
        ;;
    "continue")
        continue_function
        ;;
    "reload")
        reload_function
        ;;
    "restart")
        restart_function
        ;;
    "stop")
        stop_function
        ;;
    "status")
        status_function
        ;;
    "config")
        config_function
        ;;
    "test")
        test_function
        ;;
    *)
        echo "argument not recognised"
        echo "
    lamp start: starts vm and all necessary services, then open appropriet editors, logs and sites
    lamp continue: open editors and logs from current terminal
    lamp reload: reloads apache2 on vm
    lamp restart: reboots vm then start all necessary services
    lamp restart web: restart apache2 on vm
    lamp stop: shutdown vm, then close appropriet editors, logs and sites
    lamp stop vm: shutdown vm host only
    lamp status: show status of vm, site, apache2, mysql...
    lamp config: opens configuration file"
        ;;
esac

# ==============================================================================================================================
# end of script